### ISSUE TITLE
Unclear documentation when building on Linux 

### ISSUE THREAD

**Issue by paxsali** [DiegoMagdaleno/BSDCoreUtils#10]
Hi all,

I'm missing autogen.sh and configure in the source.
(Cloned on 2021-08-09 or 08/09/2021)

Also the docs mention the common GNU toolchain as requirements, but not cmake.
It appears to me that cmake is required though from looking at all the files in the source.

The docs don't mention cmake, nor the steps required for compiling all (or individual) BSD variants.

Am I missing something obvious? Cuz I don't know how to use this.

The reason I'm highly interested in BSDCoreUtils (and plan9 etc.) is because I wanna be able to test my compat shell scripts with non-GNU binaries, but without "heavy" VMs or docker images of common BSD OSes.

I'm on Ubuntu 20.4.2 LTS (for stable) and also OpenSUSE Tumbleweed (for bleeding edge).

Any more infos required, I'll provide them.

Thanks for your answers in advance.

**Comment by DiegoMagdaleno** [comment]
Yes, that correct, I sadly haven't updated the documentations, and I would be more than glad if a pull request was submitted (or not I might be able to update this)

To build now you need to run:

```
mkdir build && cd build
cmake .. 
make 
make install
```

I don't recommend running make install because it might conflict with your utils, if you wish to install it to a certain directory run

```
make install DESTDIR=/your/target
```

Please report any issues you might encounter.

And sorry for the late reply. :)

**Comment by DiegoMagdaleno** [comment]
@paxsali This issue should be fixed in the docs in the latest build. Tell me if you encounter any errors.

**Comment by paxsali** [comment]
@DiegoMagdaleno 
Thanks for the update. That was very helpful.

I managed to build and install the tools in my local home directory with no root priviledges.
Only for the installation of the build-deps I needed root/sudo.

I documented the steps that I took and as a "give back" I'm sharing them here:

# How to install BSDCoreUtils on Ubuntu 20.04.2 LTS:

## Install build dependencies
```
$ sudo apt-get install -y cmake
$ sudo apt-get install -y libbsd-dev
```

## Clone the Repo

```
$ cd ~/local/Git-Repositories
$ git clone https://github.com/DiegoMagdaleno/BSDCoreUtils
```

## Build BSDCoreUtils

```
$ cd ~/local/Git-Repositories/BSDCoreUtils
$ mkdir build
$ cd build
$ cmake .. 
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Looking for required package OpenSSL
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")
Looking for required package libbsd
-- Checking for module 'libbsd-overlay'
--   Found libbsd-overlay, version 0.10.0
-- Could NOT find FTS (missing: FTS_LIBRARY)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paxsali/local/Git-Repositories/BSDCoreUtils/build
$ make -j$(nproc)
$ make install DESTDIR=/home/paxsali/.opt/.realopt/BSDCoreUtils

$ cd /home/paxsali/.opt
$ ln -s .realopt/BSDCoreUtils .
```

## to activate BSDCoreUtils environment in current shell...
(you can alias this and/or put it in a script and source it)

```
export MANPATH="/home/paxsali/.opt/BSDCoreUtils:${MANPATH}"
export PATH="/home/paxsali/.opt/BSDCoreUtils/usr/local/bin:${PATH}"
env PS1="(BSDCoreUtils) ${PS1}" -- bash --noprofile --norc
```

# What has been installed?

```
(BSDCoreUtils) paxsali@BIGRIG:[~]─┤M✔├─[origin/msys2_prod]─$ ls -l .opt/BSDCoreUtils/
total 40
drwx------  2 paxsali  paxsali  4096 Aug 11 00:34 man1
drwx------  2 paxsali  paxsali  4096 Aug 11 00:34 man6
drwx------  2 paxsali  paxsali  4096 Aug 11 00:34 man7
drwx------  2 paxsali  paxsali  4096 Aug 11 00:34 man8
drwx------  3 paxsali  paxsali  4096 Aug 11 00:34 usr

(BSDCoreUtils) paxsali@BIGRIG:[~]─┤M✔├─[origin/msys2_prod]─$ ls .opt/BSDCoreUtils/usr/local/bin
arch     chmod    csplit   dirname  expand   fmt      join     mkdir    nice     pathchk  pwd      rmdir    stat     test     tsort    users    xinstall
basename chroot   cut      du       expr     fold     ln       mknod    nl       pr       readlink sleep    stty     touch    tty      wc       yes
bsdvers  comm     date     echo     factor   head     logname  mktemp   nohup    printenv realpath sort     sync     tr       uname    who
cat      cp       dd       env      false    id       ls       mv       paste    printf   rm       split    tee      true     uniq     xargs

(BSDCoreUtils) paxsali@BIGRIG:[~]─┤M✔├─[origin/msys2_prod]─$ bsdvers

       _____                    The OpenBSD coreutils project. v6.7
    \-     -/                   Copyright (C) 1997-2020 The OpenBSD Project
 \_/         \                  Copyright (C) 2017-2020 David Cantrell
 |        O O |                 Copyright (C) 2019-2020 Diego Magdaleno
 |_  <   )  3 )                 Copyright (C) 2018-2020 Jim Bair
  / \         /
    /-_____-\
                                This set of programs may be freely redistributed under
                                The terms of the OpenBSD license.
```
Works like a charm. However, I will ofc test this extensively and report back, if anything comes up.

Thanks again.

EDIT: I only noticed this message `-- Could NOT find FTS (missing: FTS_LIBRARY)`. I don't know... is that important? Bad? Can be ignored?

**Comment by DiegoMagdaleno** [comment]
Yes, it can be safety ignored, is it is supliend by your libc.

Thanks :)

I'll close this
