### ISSUE TITLE
Alpine build

### ISSUE THREAD

**Issue by andy5995** [DiegoMagdaleno/BSDCoreUtils#18]
@DiegoMagdaleno would you like some help with the alpine build in the CI?

**Comment by DiegoMagdaleno** [comment]
Thank you, however, the issue seems to be with building the fts library as it was removed from the Alpine repositories.

However, I think I already know how to fix it.

Lemme see if I am able to fix it, else I might need a little of help.

**Comment by DiegoMagdaleno** [comment]
This is fixed as of 8f1105a7a81b7192265e35a7c015b7b0a8e4c874. Thanks a lot for all the contributions to the CI :D

**Comment by andy5995** [comment]
Nice!
